### ISSUE TITLE
On last step in cart it gets the default product price

### ISSUE THREAD

**Issue by quintenbuis** [danrcoull/Magento2-Product-Price-List#8]
Magento updates the `quote_item` table at the last step with the default product price.

**Comment by quintenbuis** [comment]
Found out so far: 
In file `vendor/magento/module-quote/Model/Quote/TotalsCollector.php` it collects the address totals in methods `collect` and `collectAddressTotals` but doesn't pay attention to the priceLists.

Working on a fix.

**Comment by quintenbuis** [comment]
Somewhere in Magento there is a plugin on `getShippingAddress()`  in the file `vendor/magento/module-quote/Model/Quote.php` which returns the totals without the PriceList. I can't figure out where it is or how to fix it.

**Comment by yecraftsman** [comment]
The plugin dependency injection only applies to the frontend area and does not include the API area. 
Trying to copy etc/frontend/di.xml on etc/webapi_rest/di.xml if not, put it at the global area etc/di.xml
